//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspRecipeStorage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.RecipeSteps = new HashSet<RecipeStep>();
        }
    
        public int Id { get; set; }
        public int IngredientTypeId { get; set; }
        public int MeasureTypeId { get; set; }
        public int Amount { get; set; }
    
        public virtual ICollection<RecipeStep> RecipeSteps { get; set; }
        public virtual MeasureType MeasureType { get; set; }
        public virtual IngredientType IngredientType { get; set; }
    }
}
