//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspRecipeStorage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsSetRow
    {
        public int Id { get; set; }
        public int IngredientTypeId { get; set; }
        public Nullable<int> Amount { get; set; }
        public int MeasureTypeId { get; set; }
        public int IngredientsSetId { get; set; }
    
        public virtual IngredientsSet IngredientsSet { get; set; }
        public virtual IngredientType IngredientType { get; set; }
        public virtual MeasureType MeasureType { get; set; }
    }
}
