//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspRecipeStorage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentRecipeStep
    {
        public int Instrument_Id { get; set; }
        public int RecipeStep_Id { get; set; }
        public int InstrumentCount { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual RecipeStep RecipeStep { get; set; }
    }
}
