//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspRecipeStorage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureConversion
    {
        public int Id { get; set; }
        public int MeasureTypeFirstId { get; set; }
        public int MeasureTypeSecondId { get; set; }
        public double Ratio { get; set; }
        public int IngredientTypeId { get; set; }
    
        public virtual MeasureType MeasureSecondType { get; set; }
        public virtual MeasureType MeasureFirstType { get; set; }
        public virtual IngredientType IngredientType { get; set; }
    }
}
