//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspRecipeStorage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeStep = new HashSet<RecipeStep>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DishTypeId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual DishType DishType { get; set; }
        public virtual ICollection<RecipeStep> RecipeStep { get; set; }
        public virtual User User { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
